# -*- coding: utf-8 -*-
"""seoul_elderly_population_map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AukOPmNMOjQbaz6V-3q15WfQAI3PZcSG
"""

import pandas as pd
import folium
import json

geojson_path = 'D:/project/대한민국 행정동 경계.geojson'
csv_path = 'D:/project/65.csv'

with open(geojson_path, 'r', encoding='utf-8') as file:
    seoul_geo = json.load(file)

population_data = pd.read_csv(csv_path)

population_data.columns = ['Index', '시군구', '읍면동', '고령자수']

population_data['고령자수'] = population_data['고령자수'].str.replace(',', '').astype(int)

population_data = population_data.drop(columns=['Index'])

population_data['adm_nm'] = '서울특별시' + ' ' + population_data['시군구'] + ' ' + population_data['읍면동']

m = folium.Map(location=[37.5665, 126.9780], zoom_start=11)

folium.Choropleth(
    geo_data=seoul_geo,
    name="choropleth",
    data=population_data,
    columns=["adm_nm", "고령자수"],
    key_on="feature.properties.adm_nm",
    fill_color="Reds",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="고령자수"
).add_to(m)

folium.LayerControl().add_to(m)

m.save('D:/project/seoul_elderly_population_map.html')

