# -*- coding: utf-8 -*-
"""sheltermap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nrp_ZMTjELGMyVkZicu938kIfjZjvZ-b
"""

import pandas as pd
import folium
from folium.plugins import HeatMap

file_path_new = './무더위 쉼터 위도 경도.csv'
data_new = pd.read_csv(file_path_new)

data_relevant = data_new[['field2', '_X', '_Y']].rename(columns={'field2': 'Address', '_X': 'Longitude', '_Y': 'Latitude'})
data_relevant['District'] = data_relevant['Address'].apply(lambda x: x.split(' ')[1])
district_counts = data_relevant['District'].value_counts().reset_index()
district_counts.columns = ['District', 'Count']

seoul_map = folium.Map(location=[37.5665, 126.9780], zoom_start=11)

for idx, row in data_relevant.iterrows():
    folium.CircleMarker([row['Latitude'], row['Longitude']],
                        radius=5,
                        color='blue',
                        fill=True,
                        fill_color='blue',
                        fill_opacity=0.6).add_to(seoul_map)

heat_data = [[row['Latitude'], row['Longitude']] for index, row in data_relevant.iterrows()]
HeatMap(heat_data).add_to(seoul_map)

from google.colab import drive
drive.mount('/content/drive')

seoul_map.save('/content/drive/MyDrive/MBC_Project.html')

